on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request:

name: MeshMap Screenshot Service

jobs:
  meshmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Run the MeshMap screenshot service
    steps:
      - name: Set PR number
        run: |
          export pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NO=$pull_number" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: layer5labs/meshmap-snapshot
      - id: test_result
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          providerToken: ${{ secrets.MESHERY_PROVIDER_TOKEN }}
          cypressRecordKey: ${{ secrets.CYPRESS_RECORD_KEY }}
          applicationId: 35e32646-71a2-4d55-a4fa-dfc18a079f56
          prNumber: ${{ env.PULL_NO }}